### ISSUE TITLE
Not really an issue, but didnt find a dedicated messenger, feel free to dismiss

### ISSUE THREAD

**Issue by Jackall4BDN** [Eimaen/MusixmatchClientLib#17]
I am currently asking around in the MxM Curator Community for better ways to upload syncs, seeing how you documented your API-research quite well so far, i was curious, if you ever considered using it to develop more indepth tools for lyrics-synchronisation with it, and if you also got an example i could work with (if already implemented in your code) to submit word for word synchronisations

**Comment by Eimaen** [comment]
Yes, I tried to make a custom client, but put this idea aside as Musixmatch developers started working on new tools for contributors. I'm sure they'll do it better ;)


My library already has tools for word sync. If you are interested in this idea, you can try it yourself.

You may check [this](https://github.com/Eimaen/MusixmatchClientLib/blob/49c7f2404db617c9c19d76f1380029fd54c3f5e6/MusixmatchClientLib/MusixmatchClient.cs#L507) function and [sample project](https://github.com/Eimaen/MusixmatchClientLib/tree/master/MusixmatchClientLib.Sample) (I know that the library is missing documentation at the moment, so feel free to contact me on discord: Eimaen#0001)
