### ISSUE TITLE
Authentication failed, probably because of invalid/missing API key.

### ISSUE THREAD

**Issue by skuill** [Eimaen/MusixmatchClientLib#21]
Hello!
First, I want to say thank you for your library and work! :)

I signed up for Musixmatch, got an API Key to use in requests.
![image](https://github.com/Eimaen/MusixmatchClientLib/assets/19705282/3d31875c-1169-4e8a-b31f-6ce6f22f2e22)

I tried using their token in the library but get the following error when try SongSearch method:
`Authentication failed, probably because of invalid/missing API key.`

Example of code with a MusixmatchClient available below:
![image](https://github.com/Eimaen/MusixmatchClientLib/assets/19705282/faf6491e-ea95-49f4-a32d-f8ebf65f63f5)

If I tried to initialize the client without a token like:
```
var musixmatchToken = new MusixmatchToken();
...
var clietn = new MusixmatchClient(musixmatchToken);
```
Then everything works as expected.

Could you please tell me what could be wrong in case with an API Key from Musixmatch site?

**Comment by Eimaen** [comment]
Hi, @skuill! The token you used in your project is for official API (which by the way has major [limits](https://developer.musixmatch.com/plans)). This library will not work with official tokens, you must obtain one that can be used with this lib from mxm's mobile, desktop or web app, or generate and cache a new one as described [here](https://github.com/Eimaen/MusixmatchClientLib/blob/dev/MusixmatchClientLib.Example/Program.cs#L14). If you still have questions, feel free to contact me on Discord: `Eimaen#7264`.

UPD: Misread the issue, edited the comment.

**Comment by skuill** [comment]
Hi @Eimaen !
Thank you for the explanation. Will close the issue.
