### ISSUE TITLE
Generating a new token through a constructor call hangs indefinitely

### ISSUE THREAD

**Issue by skuill** [Eimaen/MusixmatchClientLib#25]
Hi @Eimaen !
I found the following problem:
When I tried to get a new token by calling the following constructor:
![image](https://github.com/Eimaen/MusixmatchClientLib/assets/19705282/ac846918-edbd-454f-9169-7aa7753994f4)

No other code below this call is executed, i.e. hangs somewhere inside the creation of the object and hangs indefinitely.

I use the following code:
`var musixmatchToken = new MusixmatchToken();`
Here:
https://github.com/skuill/LyricsScraperNET/blob/main/LyricsScraperNET/Providers/Musixmatch/MusixmatchTokenCache.cs#L64

Could you take a look please?

**Comment by Eimaen** [comment]
The hang itself is now fixed, however the source of the problem's still out there. I'll open a new issue soon.
